name: Generate
on:
  schedule:
    - cron: '0 0 * * 0' # every Sunday at midnight
  workflow_dispatch:
jobs:
  generate:
    permissions:
      contents: write
      pull-requests: write
    env:
      VERSION: ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: generate
        id: generate
        run: |
          npm install
          npm update --save
          ./.github/workflows/scripts/generate.sh
      - name: create release branch
        if: steps.generate.outputs.version != ''
        run: |
          # setup git credentials as github actions bot
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name "build bot"
          git checkout -b "release/v${{ steps.generate.outputs.version }}"
          git add .
          git commit -m "chore: release v${{ steps.generate.outputs.version }}"
          git push origin "release/v${{ steps.generate.outputs.version }}"
      - uses: actions/github-script@v8
        if: steps.generate.outputs.version != ''
        with:
          script: |
            const version = '${{ steps.generate.outputs.version }}';
            const changeNotesVersion = version.split('.').slice(0, 2).join('-');
            const appStoreConnectChangeNotesUri = `https://developer.apple.com/documentation/appstoreconnectapi/app-store-connect-api-${changeNotesVersion}-release-notes`;
            const { data: pullRequest } = await github.rest.pulls.create({
              title: `chore: release v${version}`,
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: 'main',
              head: `release/v${version}`,
              body: `This PR was automatically generated by the build bot\n[App Store Connect API ${version} Change Notes](${appStoreConnectChangeNotesUri})`,
            })
            console.log(`PR created: ${pullRequest.html_url}`)
