name: Publish
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
      - run: |
          npm ci
          npm run build
          # check if the last release is the same as the current version
          lastVersion=$(npm show @rage-against-the-pixel/app-store-connect-api version)
          version=$(node -p "require('./package.json').version")
          if [ "$version" = "$lastVersion" ]; then
            echo "No changes detected"
            exit 0
          fi
          npm publish --access public
